### ISSUE TITLE
Interferes with drop down menu

### ISSUE THREAD

**Issue by edhardt** [aaronhuisinga/wordpress-employment#3]
Hi,

Firstly - fantastic plugin.

However, it seems like there's an issue with the compatibility of the plugin and my site where the pages powered by the plugin prevent my drop down menu from displaying. 

Any ideas?

Thanks

**Comment by aaronhuisinga** [comment]
The old version of the plugin was most certainly conflicting with JS and CSS on several blogs. This has been fixed in 0.5.0 as files are now properly namespaced and registered via WordPress functions.
